apiVersion: v1
kind: Service
metadata:
  name: edit-1
  namespace: default
  labels:
    app: edit-1
spec:
  type: ClusterIP
  selector:
    app: edit-1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edit-1
  namespace: default
  labels:
    app: edit-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edit-1
  template:
    metadata:
      labels:
        app: edit-1
    spec:
      containers:
        - name: edit-1-container
          image: satyamp07/waitlist:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 200m
          env: []
      imagePullSecrets:
        - name: scoutflo-satyam-docker-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edit-1
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: edit-1-sdszovr9u9h3quea6j6xpcec-9necr.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: edit-1
                port:
                  number: 80
  tls:
    - hosts:
        - edit-1-sdszovr9u9h3quea6j6xpcec-9necr.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
